### PR TITLE
Switch the plugin to use Cowboy REST

### PR DESCRIPTION
**Pull request by essen**
Part of rabbitmq/rabbitmq-federation-management#3

### CODE REVIEW

**Comment by michaelklishin** [comment]
When I try to add an upstream via management UI, the server responds with `400 Bad Request`. All mandatory fields are filled out:

 * I have a separate vhost, `vhost1`.
 * URI is `amqp://127.0.0.1/vhost1`
 * Upstream name is `upstream1`

**Comment by essen** [comment]
It's probably the issue I had on the channel earlier today. The federation plugin is not a dependency of federation-management (not sure why, maybe it should be) and so isn't loaded on 'make run-broker'.

**Comment by michaelklishin** [comment]
I tried

```
make run-broker PLUGINS='rabbitmq_management rabbitmq_federation rabbitmq_federation_management'
```

There were no missing plugin dependency errors. I think the plugin is running just fine. Try it for yourself.

**Comment by essen** [comment]
Ran your command, added vhost1, adding permissions for guest, went to add the upstream with the values you provided, no error and it shows up fine in the list.

I can look further tomorrow.

**Comment by michaelklishin** [comment]
OK, thanks, I will give it a try in a few more environments.

**Comment by michaelklishin** [comment]
Somehow things work in two other environments :)

**Pull request merged**
